# Dependencies
markdown:         redcarpet
highlighter:         pygments

# Make strikethrough work with redcarpet
redcarpet:
  extensions: ["strikethrough"]

# Permalinks
permalink:        /:title/

# Setup
title:            Fraktar
tagline:          'Crafting Things.'
description:      'Overcoming the terminal window fear.'
url:              http://fraktar.com

#author:
 # name:           'Fraktar'
# url:            https://twitter.com/fraktar

#gems: [jekyll-paginate, jekyll/tagging]
gems:
  #- jekyll/tagging 
  - jekyll-paginate
  
paginate:         5
paginate_path: "/:num/"
# Custom vars
#github:
# repo:  https://github.com/fraktar/fraktar.com.git

# Excludes
exclude: ['LICENSE.md', 'README.md', 'CNAME', "package.json", "node_modules"]

#tag_page_layout: tag_page
#tag_page_dir: tag
#tag_permalink_style: pretty
#ignored_tags: [tags,to,ignore]
#tag_page_data:
#  sitemap: false